-- IARS v3.7.0
-- Manual administrator-approved username login (no SMS provider required)

create extension if not exists pgcrypto;

create table if not exists public.iars_users (
    id uuid primary key default gen_random_uuid(),
    full_name text not null,
    username text not null,
    contact_number text not null default '',
    password_salt text not null,
    password_hash text not null,
    status text not null default 'Pending'
        check (status in ('Pending', 'Code Issued', 'Active', 'Suspended', 'Deactivated')),

    activation_code_hash text not null default '',
    activation_code_expires_at timestamptz,
    activation_attempts integer not null default 0,
    activated_at timestamptz,

    reset_requested boolean not null default false,
    reset_code_hash text not null default '',
    reset_code_expires_at timestamptz,
    reset_attempts integer not null default 0,

    failed_login_attempts integer not null default 0,
    locked_until timestamptz,
    last_login_at timestamptz,

    approved_at timestamptz,
    approved_by text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists iars_users_username_uidx
    on public.iars_users (username);

create index if not exists iars_users_status_idx
    on public.iars_users (status);

create index if not exists iars_users_reset_requested_idx
    on public.iars_users (reset_requested)
    where reset_requested = true;

create table if not exists public.iars_auth_log (
    id bigint generated by default as identity primary key,
    event_type text not null,
    username text not null default '',
    user_id uuid references public.iars_users(id) on delete set null,
    success boolean not null default true,
    details text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists iars_auth_log_created_at_idx
    on public.iars_auth_log (created_at desc);

create index if not exists iars_auth_log_username_idx
    on public.iars_auth_log (username);

-- The app accesses these tables only through the server-side service-role key.
-- Browser-side anon/authenticated access is deliberately blocked.
alter table public.iars_users enable row level security;
alter table public.iars_auth_log enable row level security;

revoke all on table public.iars_users from anon, authenticated;
revoke all on table public.iars_auth_log from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.iars_users to service_role;
grant select, insert, update, delete on table public.iars_auth_log to service_role;
grant usage, select on all sequences in schema public to service_role;
